# MediaWiki with MariaDB
#
# Access via "http://localhost:8080"
#   (or "http://$(docker-machine ip):8080" if using docker-machine)
version: '3'
services:
  mediawiki:
    image: wikimedia/mediawiki
    restart: always
    environment:
      - MEDIAWIKI_DB_TYPE=mysql
      - MEDIAWIKI_DB_HOST=database
      - MEDIAWIKI_DB_USER='wiki'
      - MEDIAWIKI_DB_PASSWORD='password'
      - MEDIAWIKI_SITE_SERVER=http://localhost:8080
      - MEDIAWIKI_SITE_NAME="My  Wiki"
      - MEDIAWIKI_SITE_LANG=en
      - MEDIAWIKI_ADMIN_USER=admin
      - MEDIAWIKI_ADMIN_PASS=password123
      - MEDIAWIKI_UPDATE=true
      - MEDIAWIKI_ENABLE_SSL=false
    links:
      - database
    ports:
      - 8080:80
    volumes:
      - /srv/wiki/images:/var/www/html/images
      # uncomment after wiki setup
      #- /srv/wiki/LocalSettings.php:/var/www/html/LocalSettings.php 
  database:
    image: mysql
    restart: always
    ports:
      - 3306:3306  
    volumes:
      - /srv/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'wikidatabase'
      MYSQL_USER: 'wiki'
      MYSQL_PASSWORD: 'password'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
